package gym;

import javafx.fxml.FXML;

import java.util.ArrayList;

import javafx.event.ActionEvent;

public class fxmlController {

	public Gym gymi = new Gym(new ArrayList<Training_Device>() , new ArrayList<Trainee>());
	public ArrayList<Exercise> tempEx = new ArrayList<Exercise>();
	// Event Listener on Button.onAction
	@FXML
	public void func(ActionEvent event) {
		// TODO Autogenerated
	}
}
